manifest:
  self:
    path: mainRoot
#    west-commands: scripts/west-commands.yml

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

    - name: cmsis-svd
      url-base: https://github.com/cmsis-svd
      
    - name: bl
      url-base: git@github.com:BiologIC-Colin

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v4.4.0
      import:
         name-allowlist:
            - cmsis
            - cmis_6
            - cmis-dsp
#            - hal_nxp
            - hal_stm32
            - hal_rpi_pico
            - mcuboot
            - picolibc
            - libc3
            - loramac-node
            - segger
      
    - name: cmsis-svd-data
      remote: cmsis-svd
      revision: main
      
    - name: loraScarer
      remote: bl
      revision: master
      path: apps/loraScarer

    - name: picowifi
      remote: bl
      revision: master
      path: apps/picowifi

    # - name: pico_camera_slider
    #   remote: bl
    #   revision: master
    #   path: apps/slider

    - name: boards_zephyr
      remote: bl
      revision: master
      path: modules/boards

    - name: drivers_zephyr
      remote: bl
      revision: master
      path: modules/drivers
      
    - name: libs_zephyr
      remote: bl
      revision: master
      path: modules/lib
