manifest:
#  self:
#    path: example-application
#    west-commands: scripts/west-commands.yml

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

    - name: cmsis-svd
      url-base: https://github.com/cmsis-svd
      
    - name: bl
      url-base: git@github.com:BiologIC-Colin
      
  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: main
      import:
         name-allowlist:
            - cmsis
            - cmsis_6
            - cmsis-dsp
            - hal_ambiq
            - hal_rpi_pico
            - hal_infineon
            - mcuboot
            - picolibc
            - libc3
      
    - name: cmsis-svd-data
      remote: cmsis-svd
      revision: main

# Multiple apps can be placed in the workspace/apps folder. Bit like zephyr/samples.

    - name: dotstar_zephyr_app
      remote: bl
      revision: master
      path: apps/dotstar      

    - name: picowifi
      remote: bl
      revision: master
      path: apps/picowifi

    - name: pico_camera_slider
      remote: bl
      revision: master
      path: apps/slider

    # Repositories for custom boards and drivers.

    - name: boards_zephyr_home
      remote: bl
      revision: master
      path: modules/boards

    - name: drivers_zephyr_home
      remote: bl
      revision: master
      path: modules/drivers
